version: '3.8'

volumes:
  test_volume:

services:
  mysql:
    image: mysql:8.2.0
    container_name: tracking-delivery
    volumes:
      - test_volume:/var/lib/data
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=tracking-delivery
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  delivery-tracker:
    build:
      context: docker/delivery-tracker
      dockerfile: Dockerfile
    container_name: delivery-tracker
    hostname: delivery-tracker
    ports:
      - "4000:4000"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-stream
    volumes:
      - test_volume:/etc/rabbitmq/
      - test_volume:/var/lib/rabbitmq/
      - test_volume:/var/log/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "RabbitMQ-My-Cookies"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "1234"